### PR TITLE
update github client dependencies to fix auth issues

### LINKED ISSUE #3: Github App Authentication failed
Github endpoints for app authentication changed and old routes are no longer supported. See blog post:
https://developer.github.com/changes/2018-08-16-renaming-and-deprecation-of-github-app-installation-access-token-route/

Checkr needs to be updated to use the current API endpoints.

### PR DESCRIPTION
**Pull request by tnaroska**
Fixes #3 

included changes
- update to golang 1.19
- upgrade bradleyfalzon/ghinstallation for https://github.com/bradleyfalzon/ghinstallation/pull/17
- upgrade google/go-github for final version of Github Check Runs API
- minor code adaptions to changed APIs

### CODE REVIEW

**Comment by AnalogJ** [comment]
Hey Timo! Long time no see :) 

Well that's annoying. I'll merge this and add you as a collaborator on this repo so you have access to make changes.

**Comment by tnaroska** [comment]
Hey, thanks man! Hope you're doing good!
Yeah, da checkr is still in use here 😀

Is there any automation to create a new release? I see capsule.yml in the repo, but not sure how to trigger it.

**Comment by AnalogJ** [comment]
ah, let me fix that, I have a couple of handy github-actions that I use

**Comment by AnalogJ** [comment]
done, binaries have been attached to the release as well. 
If you need any other GOARCH versions, just add them to the github action release.yaml

**Comment by tnaroska** [comment]
Awesome!!

**Pull request merged**
